### ISSUE TITLE
Retrieve cricket data through API

### ISSUE THREAD

**Issue by CherineJ** [LTER-LIFE/FDFDT#3]
The crickets dataset is currently stored at the DANS Data Station. To start working on the data, the dataset was first downloaded locally but the aim is to retrieve it through an API. 
As the Data Station is based on Dataverse, we can potentially reuse parts of the code we used to retrieve the bud burst data from the Demo dataverse.

**Comment by karlines** [comment]
It would be nice if you would write a more general function then that retrieves any data set from this dataverse.

**Comment by CherineJ** [comment]
Apparently the dataverse API is also the underlying API for the [DANS datastation](https://lifesciences.datastations.nl/). Therefore our previous code, that was already general and could retrieve any dataset from the [dataverse.nl](https://dataverse.nl/) or [demo.dataverse.nl](https://demo.dataverse.nl/), can also be used as it is for the data station. The data station however requires another API key, which can be obtained when login in. Hence, only the DOI of the dataset, the server and the according API key need to be entered  for every dataset individually when using the function to retrieve the data.
